matrix:
  include:
    - language: node_js
      node_js:
        - '10'
        - '8'
        - '6'
      before_install:
        - cd web/
      install:
        - npm install
      script:
        - npm run lint
        - npm run build

    - language: go
      go:
        - 1.11.x
      env:
        - GO111MODULE=on
      install: true
      
      script:
        - go test -race -coverprofile=coverage.txt -covermode=atomic  ./...
      after_success:
        - bash <(curl -s https://codecov.io/bash)
